name: Container Build

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    - cron: '0 1 * * *'
    
permissions: write-all
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Registry Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert IMAGE_NAME to lowercase
      id: lowercase
      run: echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and Push
      run: docker buildx build --platform linux/amd64 -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" --push -f Dockerfile .